openapi: 3.0.0
info:
  title: UNWE - Unemployment Web Visualizer
  description: API to get official data about unemployment in Romania.
  version: 1.0.0
servers:
  - url: localhost
paths:
  /query:
    get:
      summary: Queries the database to get various unemployment data.
      description: Returns all available data about the counties specified, from the specified start date until the most recent date, taking into account the mentioned categories.
      parameters:
        - name: from-json 
          in: query
          required: false
          schema:
            type: boolean
          description: Allows the request parameters to be sent and parsed from the request body in JSON format
        - name: start-date
          in: query
          required: true
          schema:
            type: string
            format: date
          example: "2020-10-01"
        - name: counties
          in: query
          required: true
          schema:
            type: array
            items: 
              type: string
          example: [iasi, bacau, botosani]
        - name: categories
          in: query
          required: false
          schema:
            type: array
            items: 
              type: string
          description: If left empty, 'total' category is assumed. Categories may be one (or more) from the following - total, sex, compensation, environment, age, education
      responses:
        '200':    # status code
          description: A JSON array of unemployment data per months and counties
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/QueryResponse'
                  
                    
        '400':
          description: Bad request. Probably due to illegal or missing request parameters
          content: 
            text/plain:
              example: "At least one county must be specified!"
        '500':
          description: Internal server error. Probably due to connection issues with the Database or other unexpected errors.
          content:
            text/plain:
              example: "DB error"
              
  /signup:
    post:
      summary: returns a token that can be used to request a database refresh
      responses:
        '200':
          description: returns the generated token
          content:
            text/plain:
              example: FfLotqhVDEVZqh14i6Fa8XjfrsPIgs1f
        '500':
          description: Internal server error. Possibly because of connectivity issues with the database.
          
              
  /refreshdb:
    post:
      summary: Refreshes the Database with the most recent data available
      description: The data is taken directly from the official <a href="https://data.gov.ro/dataset?q=somaj&sort=metadata_modified+desc">Romanian government website</a>
      security:
        - apiKey: 
          - "write: refresh"
      responses:
        '200':
          description: ok
          content:
            text/plain:
              example: DB refreshed successfully
        '500':
          description: Internal server error. Possibly because of connectivity issues with the database or because of issues with the government website.
  
  /resetTokens:
    post:
      summary: Resets the token database. For internal use only.
      security:
      - superSecretPassword:
        - "write: reset"
      responses:
        '200':
          description: ok
          content:
            text/plain:
              example: Reset successful
        '500':
          description: Internal server error. Possibly because of connectivity issues with the database.
          
components:
  securitySchemes:
    apiKey:
      name: Authorization
      type: apiKey
      in: header
    superSecretPassword:
      name: Authorization
      type: apiKey
      in: header

  schemas:
    QueryResponse:
      type: object
      properties:
        luna: 
          type: string
          format: date
        judet:
          type: string
          example: iasi
        nr_total:
          type: integer
          example: 3875
        nr_femei:
          type: integer
        nr_barbati:
          type: integer
        rata_total:
          type: number
          format: float
          minimum: 0
          maximum: 100
          example: 3.1
        rata_femei:
          type: number
          format: float
          minimum: 0
          maximum: 100
          example: 2.5
        rata_barbati:
          type: number
          format: float
          minimum: 0
          maximum: 100
          example: 0.6
        nr_indemnizati:
          type: integer
        nr_neindemnizati:
          type: integer
        nr_urban_total:
          type: integer
        nr_femei_urban:
          type: integer
        nr_barbati_urban:
          type: integer
        nr_rural_total:
          type: integer
        nr_femei_rural:
          type: integer
        nr_barbati_rural:
          type: integer
        nr_fara_studii:
          type: integer
        nr_primar:
          type: integer
        nr_gimnazial:
          type: integer
        nr_liceal:
          type: integer
        nr_postliceal:
          type: integer
        nr_profesional:
          type: integer
        nr_universitar:
          type: integer
        nr_sub_25:
          type: integer
        nr_25_29:
          type: integer
        nr_30_39:
          type: integer
        nr_40_49:
          type: integer
        nr_50_55:
          type: integer
        nr_peste_55:
          type: integer
      required:
        - luna
        - judet
        - nr_total
          
          
          
          
          
          
          
          
          
          
          
          
          